USE `expert`;

CREATE TABLE `contacts` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(20),
	`surname` VARCHAR(20),
	`login` VARCHAR(255) NOT NULL UNIQUE,
	`email` VARCHAR(255) NOT NULL UNIQUE,
	`phone` VARCHAR(255) NOT NULL UNIQUE,	
	PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARACTER SET `utf8`;

